### ISSUE TITLE
Spark install fails - dependency issue

### ISSUE THREAD

**Issue by mehany** [laravel/spark#146]
Hi, I was about to Spark but got no joy because of a simple dependency issue. Current version requires Laravel\Cashier v6.0 and I have v5.0 . I am fine with a previous versjion of spark ( like 0.2.1 ) which requires  Laravel\Cashier v5.0 but I am not sure how to specify the Spark version being installed with the <code> spark install </code> command.

**Comment by pablocabana** [comment]
Samething here :(

**Comment by jasonherndon** [comment]
Same thing here... I noticed after an ```npm update``` that Gulp was also giving an error when attempting to compile the scripts. I figured updating Spark may help? But I'm not sure

**Comment by jasonherndon** [comment]
For me... changing the following in my app.js file helped.

```
require('laravel-spark/core/dependencies');
require('./spark/components')
```

to 

```
require('laravel-spark/core/bootstrap');
require('laravel-spark/core/components');
``` 

This at least got Gulp to pass and compile everything through Browserify without error, the Vue to initialize as well - not sure about the other components/modules being correctly setup but I'm assuming since it passed Gulp/Browserify there's at least no errors in file paths. This may at least be helpful until any new update to the code/documentation comes out

**Comment by mehany** [comment]
@jasonherndon I feel like you have a different setup! The issue is running <code>spark install</code> does not install via <b>composer</b>.

**Comment by mikebronner** [comment]
@mehany I have not used the `spark install` command in quite some time, and don't see that it is necessary at this point (unless additional functionality has been added to it recently). All it really does is set the service provider in `config/app.php` and run `artisan spark:install`.

So my method of installing spark is as follows:
1. `composer require laravel/spark:0.2.1` (not using the latest versions due to L5.2 requirements).
2. Register the spark service provider in `config/app.php`:
  ```php
          Laravel\Spark\Providers\SparkServiceProvider::class,
  ```
3. Run `php artisan spark:install`.

At this point all should be as normal. :)

**Comment by jasonherndon** [comment]
@mehany - my apologies. I should've noted that I was working on an existing spark setup and, after the npm update updated Spark, causing my current app to fail, I tried installing a new spark application, which failed for me for the same reasons listed above. But what I really didn't need was a new application, just to fix my existing one. So I put up the code I used to do that in case anyone else came here for the same reason.

**Comment by mehany** [comment]
@mikebronner thanks very much for the solution, that got me to spark :)
@jasonherndon no worries. I was just saying 'umm these guys does not seem to use <code>spark install</code>'

So the issue on a new install still persist which @taylorotwell should be aware of! I am sure it will not be an issue within few days or weeks so I will close this

**Comment by aleppos** [comment]
@mikebronner I tried your method but I'm getting this message

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laravel\Sperk\Providers\SparkServiceProvider' not found

**Comment by mikebronner** [comment]
Typo: instead of `Sperk` try `Spark`:)

**Comment by austinkregel** [comment]
@mehany If you want the most recent version of spark, you could do what I mention in #149 [(or go to the comment)](https://github.com/laravel/spark/issues/149#issuecomment-162233011). Basically you would set your minimum stability to dev, do spark install, do a few small fixes and then be on your way using the recent version of spark.
