### ISSUE TITLE
Spark v0.2.3 does not have the migrations updated for subscriotions table

### ISSUE THREAD

**Issue by upwebdesign** [laravel/spark#149]
Anyone else able to verify this, how do you get around this issue?

**Comment by austinkregel** [comment]
### Explination
It looks like there is just a typo in the filename. it should be `2014_10_12_100000_create_subscriptions_tables.php` (the word tables needs to have an 's' on the end (which it doesn't in the actual source).  

## Solution 
Until it gets patched, you'll need to move the file to it's proper location (before you install spark!)
#### on Linux/ OSX

Navigate to your app directory.

    mv vendor/laravel/spark/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_table.php vendor/laravel/spark/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_tables.php


#### on Windows.
Navigate to the app in explorer then navigate to the `vendor`, `laravel`, `spark`, `resources`, `stubs`, `database`, `migration`.

Then rename `2014_10_12_100000_create_subscriptions_table.php` to `2014_10_12_100000_create_subscriptions_tables.php`

**Comment by upwebdesign** [comment]
Thanks @austinkregel will your solution work with `spark install`? Or are you recommending `composer require...`?

**Comment by austinkregel** [comment]
@upwebdesign What I have to do is `spark install` then do this fix and then I usually have to create a BaseUser class and modify the `App\User` class to accept the new BaseUser class because for some reason this project is using parts of Laravel 5.2 (even though that will be soon release it's a little a head of the game), 

Then I have to `spark install` again. And to get it to work right again I have to change the `App\User`'s use of the BaseUser class again.

Once I do all that then it works lol but I've done it a few times :3 xD

I know it's quite the few steps but once 5.2 is released it should work just fine xD

**Comment by upwebdesign** [comment]
@austinkregel Thanks so much I was able to get it to work per your instruction. Your explanation is the best I have seen so far!

**Comment by austinkregel** [comment]
@upwebdesign Thank you! I'm happy to hear it worked for you! :D

**Comment by hvent90** [comment]
Thanks Austin!! Your thorough explanations saved my butt.

And thank you upwebdesign for posting this question!!
