### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by michaelrtm** [laravel/spark#167]
All API requests from Spark (eg /spark/api/users/me) are failing because they need web middleware.
I'm running Spark:dev-master on Laravel 5.2.5

**Comment by nickdenardis** [comment]
This looks to be a side affect of putting the routes into middleware groups: https://github.com/laravel/spark/pull/164

Here is a [fix for the specific issue](https://github.com/nickdenardis/spark/commit/2e1cfd70403702cfda39b0ba9c9b35fe5eb888cf) with `/spark/api/users/me` but I haven't had the chance to test the rest of the api labeled routes. 

Looks like a lot of the API calls require `$this->middleware('auth', ...);`. And putting all the `/api` calls into the 'web' group seems to go against the reasoning behind separating the middleware into groups.

**Comment by danjy** [comment]
@nickdenardis I haven't really looked at the code on very closely, but don't API routes at least cut out the session state and a few other things? I remember hearing Taylor talk about the perks on the latest laravel podcast, may be worth a listen

**Comment by nickdenardis** [comment]
@danjy Yea, cutting out the unnecessary middlewares on api calls will make them faster and a few other things. 

The problem comes in when the 'auth' middleware in this case relies on:  

```
'api' => [
    \App\Http\Middleware\EncryptCookies::class,
    \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
    \Illuminate\Session\Middleware\StartSession::class,
    \App\Http\Middleware\VerifyCsrfToken::class,
    'throttle:60,1',
],
```

Without those `$this->auth->guest()` returns false or throws an error.

Specifically the [session storage](https://github.com/laravel/framework/blob/7f62d81acb2001faafb21a32544464ebfc92476c/src/Illuminate/Http/Request.php#L774):

```
RuntimeException in Request.php line 775:
Session store not set on request.
```
