### ISSUE TITLE
SparkServiceProvider not found: new laravel installation.

### ISSUE THREAD

**Issue by DanielGale** [laravel/spark#49]
I am running on Ubuntu 14.04.3 LTS. I followed the instructions from https://laravel-news.com/2015/09/laravel-spark/ to install laravel spark and the ones for the project but I get the following error in appRoot/storage/logs/laravel.log

\#0 {main}
[2015-09-17 20:40:28] local.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Laravel\Spark\Providers\SparkServiceProvider' not found' in /var/www/appRoot/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:146

The below text is placed in my app.php file in the providers array.
        /**
         * Spark Service Providers...
         */
        Laravel\Spark\Providers\SparkServiceProvider::class,

Below is the error from the browser:
FatalErrorException in ProviderRepository.php line 146:
Class 'Laravel\Spark\Providers\SparkServiceProvider' not found
in ProviderRepository.php line 146

I also checked and there is no appRoot/vendor/laravel/spark folder if there should be one. I'm not given any errors that indicate it is not copied from somewhere or found it to copy it over myself.

**Comment by gitteri** [comment]
Hey DanielGale,

I had the same problem this morning. Luckily I was working with a new Laravel installation so these are the steps I took to fix it. It is a permissions problem with composer. Also make sure php curl extension is enabled because I had a problem with that too

Try making sure php curl is enabled first and try installing again, otherwise the steps below should do it.
Not sure why this happens exactly, and you can't do 'sudo spark install'...

1. delete new Laravel app (it seemed to half install so it's easier to start fresh)
2. chown -R USER $HOME/.composer (to gain ownership over composer)
3. reinstall laravel app
4. install spark
5. done

**Comment by DanielGale** [comment]
Thanks gitteri,
 
That worked perfectly. I also noticed 'sudo spark install' didn't work. I had curl installed but not the php5-curl extension. I had to install the php5-curl extension (yesterday). That's when I ran into this error. 

After seeing your comment I noticed many of my .composer sub-folders were owned by root. I changed ownership to my user and tried running spark install without a fresh copy and got the same error. However next I removed my laravel app and started a new one. Everything ran as intended after that.

The only thing I need to do now is figure out why localhost/css/app.css isn't loading.
