### ISSUE TITLE
Broken Validation on Register Page - Cannot POST

### ISSUE THREAD

**Issue by adamgoose** [laravel/spark#8]
Currently, once I've done a fresh install & enabled teams (by adding the trait to the User model), the Registration page fails miserably. Submitting the form ends up submitting the form via GET to the same URL.

![](http://d.enge.me/o4jI+)

**Comment by adamgoose** [comment]
Note: The button text on the Register button does not show up until you click anywhere on the page. Also, the last three console messages do not show up until you click anywhere on the page either.

**Comment by kayyyy** [comment]
Did you enabled your `spark::plan` in your `SparkServiceProvider` ?

**Comment by adamgoose** [comment]
I'm not using plans at all. I want this open/free for now. I saw your issue, but it looks like you were having some other error.

**Comment by kayyyy** [comment]
Just try it - If you only have a free trial i got the same issue. After setting up a payed plan the errors are gone.

But if so then we know because this related issue :)

**Comment by adamgoose** [comment]
Still worth figuring out what the issue is. I'll give that a shot in a minute. Thanks.

**Comment by adamgoose** [comment]
@kayyyy See PR #8 for the fix. Silly typo on @taylorotwell's end.

**Comment by kayyyy** [comment]
:+1:

**Comment by razamehdi-vteams** [comment]
I had the same issue. I kept getting the error call to undefined 'callCustomValidator' function ... Turns out it was using the version v0.1.1 released on September 16. I had created plans in stripe, and had enabled them in SparkServiceProvider.php. But still registration was not working. I was able to get registration working by following these steps:

* Change following line in **composer.json** in your laravel application root from:
```
laravel/spark: "^0.1.1"
```
to

```
laravel/spark: "dev-master"
```

then i simply ran **composer update** to update to latest dev revision.
