### ISSUE TITLE
[Comment] Why Vue.js?

### ISSUE THREAD

**Issue by sgrover** [laravel/spark#80]
Thanks for Spark!  Regardless of where it goes, my dev efforts are much easier and I can focus mostly on the core purpose of my projects now, rather than the supporting elements.  So far I'm loving what I'm seeing.  The only comment I have is that Vue.js seems a little .  What I've seen of Vue so far suggests it is a great tool, but it is not part of my tool chain (nor is SASS, but that's an easy change).  So I'm left with the choice of loosing a weekend getting up to snuff on the whole Require.js approach and Vue.js as well, or removing Vue and returning to a more traditional jQuery or Javascript only approach.

While I'll be the first to admit that getting my head around Vue.js and the underlying Require.js system is probably very good for me, I do have other concerns for my projects that would be better to focus my time on.  It'd be great if there was an easy way to opt in or out of the JS framework other than an all in by default approach.

Beyond that one small point, I'm very happy with Spark!  Thanks again.

**Comment by Lidbetter** [comment]
The amount of time/effort to replace Vue with jQuery, is probably about the same as learning Vue (probably quicker to learn Vue).

The most compelling things, for me, about Vue (vs jQuery) is the two-way data binding, and how simple the whole thing is vs Ember/Angular.

You should check out: https://laracasts.com/series/learning-vuejs (all but 2 are free), this is for a slightly older version of Vue (version 1.0.0 is currently in beta) I think some syntax has been tweaked since the video. That, coupled with how the current Spark project uses Vue should give you a good starting point.

**Comment by sgrover** [comment]
Thanks for the link.  Very helpful.  I think the main issue remains though.  Should Spark be "opinionated" with regards to the JS framework in use?  But  I also ascribe to the view of "he who writes the code, makes the choices".  So if Taylor prefers Vue.js, then I probably should too, if I am going to use the product of his work.

**Comment by christophrumpel** [comment]
Spark really seems great, but I have the same opinion. Whether or not Vue.js is great and useful I would prefer to use Spark with my tools or the project tools. It is not always me who decides the tools and especially the JS Framework.

**Comment by phroggyy** [comment]
@sgrover @christophrumpel these are just in the default views. You're very much free to throw out Vue and replace that at the same time you replace the views. Most applications will stray away from the Spark default views anyway. Might use some of the magic provided, but not more. Hence, I don't see this as a problem. In the end, if Taylor had gone for Angular, someone else would've complained; had he gone for jQuery, there's someone who dislikes that, etc.

**Comment by christophrumpel** [comment]
Guess you're right. Thx

**Comment by sgrover** [comment]
Thanks @phroggyy.  I have come to a similar conclusion as I work with this.  The laracast link @christophrumpel  provided helped a good deal.  I can see that Vue is not like Angular where it is really frowned on to mix jQuery code with the Angular way.  Instead Vue seems more open to mixing solutions/approaches.  I agree with the "can't make everyone happy" sentiment.  It originally seemed that Vue was tightly integrated.  After some digging I can see it's only a few of the default views, and those are supposed to be reworked for your own project anyway.  

I'll leave this thread in place for a couple more days before I close it in case any other new Spark devs are having similar concerns...

**Comment by phroggyy** [comment]
@sgrover I think this can be closed now :blush:

**Comment by tomicakorac** [comment]
It should go without saying that, no matter what decision is made, there will always be users who are not entirely happy with it. And of course, with open-source more than with anything else, everyone is free to alternate the library to suit their needs best. So it is very clear, if we don't like Vue.js, we are free to use something else. But I think the original question hasn't been answered here: What was the reason for choosing Vue.js over something else? If the question is: "Why Vue.js?", "You are free to change it." is not answering it. We know we're free to change it, we just want to know what is the motive of the repo owners to chose it over other more prominent alternatives.

And to be clear, I'm not against Vue.js, on the contrary. My question is just so that I can be better informed.

**Comment by kirschbaum** [comment]
You might want to check out the latest episode of The Laravel Podcast, where vue.js is discussed and contrasted a bit with other js options: 

http://www.laravelpodcast.com/episodes/19454-episode-37-i-love-the-things-you-are-saying

**Comment by tomicakorac** [comment]
It will sure help. Thnks @kirschbaum

**Comment by eduardocruz** [comment]
> I hear you say "Why?" Always "Why?" You see things; and you say "Why?" But I dream things that never were; and I say "Why not?"
> George_Bernard_Shaw

Sorry, couldn't resist :)

**Comment by freedomfflow** [comment]
I'm using spark and running into problems with the loading of javascript libraries, jquery and vue.  

My issue is if I don't create an @section area where I point to jquery and vue, which I then @yield, neither library seems to be present.  
But when I do load them, I get conflicts as if they are being loaded multiple times.  

Furthermore, I see in the spark app.blade.php file which includes common/head.blade.php, it is doing an @yield('scripts','') there... So my links to jqery and vue are showing up in the <head> section, which is cool I guess, but they don't seem to function?????   but when I do an @yield in the spark app.blad.php myself at the bottom of the <body> section, it does load the libraries there and my vue stuff works, but some jquery things have conflicts (i.e. a modal call says its not a function... which according to stack overflow, means I'm loading libraries multiple times...

Sorry if this is confusing... I've been at it a while and am pretty tired, and new to spark and to vue.js...
I like vue, and I have it pulling data via an ajax call and populating a multi-select box.

BUT another clue to my problem is that when I try to click/select one or more items in the select box, the data disappears... which I confirmed in google dev tools its purging the <options> from the select box as soon as I click on any data in the select box... 

Thanks for any assistance... gonna to crash now and see if a clear head helps in the a.m.

**Comment by eduardocruz** [comment]
@freedomfflow https://laracasts.com/discuss/channels/vue

**Comment by freedomfflow** [comment]
Thanks.... so I didn't need to load vue, as its already load in spark... I
just had to modify where my js file was loaded so vue.js was already
available.

However, I have a couple other problems:

1 - My multi-select box populates, but when I try to select any data, the
'click' causes the data to be disappear (empties the select so no
options/data in it).

This is my js file I've created.  The ajax calls retrieve the data and
populate the selects.  Below the js file is part of my view file.

2 - Another problem I have is my v-on change event doesn't work.  It did
work when I had syntax  v-on:bind=  syntax, but I was using that with a
'v-for=' syntax instead of a 'v-repeat' syntax, as the vue warnings in
google dev tools instructed me to use the v-for syntax.  But that only
worked when I was manually loading vue.min.js in my header file before I
realized vue is already loaded with Spark.... Now the v-for syntax doesn't
populate my multi-selects and the v-on:bind syntax doesn't work either.

So I'm missing something, and I'm not sure what.  Spark is doing things for
me that I'm sure I don't understand and I'm not using Vue properly as a
result I assume.  Also, I don't even know which version of Vue is loaded
with Spark.. I can't figure out how to check.  I'm assuming its 1.x

Thanks so much for any assistance.  I'm new to spark, somewhat new to
laravel, and definitely new to vue, so if I'm doing some very stupid stuff
please don't be afraid to point that out.

var reports = new Vue({

    el: '#reports',

    data: {
        selected: '0',
       options: [
            { text: '-- Choose Report --', value: 0},
          { text: 'Insurance', value: 1 },
          { text: 'Charge By Client', value: 2}
       ],
      payer: null,
      patient: null
    },

   created: function() {
      this.fetchPayers();
      this.fetchPatients();
   },

   methods: {
      fetchPayers: function() {
         var self = this;
         var xhr = new XMLHttpRequest();
         xhr.open('GET', "/reports/payer_ajax_list");
         xhr.onload = function() {
            self.payer = JSON.parse(xhr.responseText);
         }
         xhr.send();
      },

      fetchPatients: function() {
         var self = this;
         var xhr = new XMLHttpRequest();
         xhr.open('GET', "/reports/patient_ajax_list");
         xhr.onload = function() {
            self.patient = JSON.parse(xhr.responseText);
         }
         xhr.send();
      },

      newSelect: function(event) {
         if (event.target.value == 2)
         {
            document.getElementById('patient_div').setAttribute('class',
'form-group show');
         }
         else
         {
            document.getElementById('patient_div').setAttribute('class',
'form-group hide');
         }
      }
   }
});

<div class="panel-body" id="reports">
    <div class="page-header">
        <h4 class="page-title">Select Report:</h4>
        <select name="report_select" v-model="selected"
class="form-control" v-on="change newSelect">
            <option v-repeat="option: options" value="@{{ option.value }}">
                @{{option.text}}
            </option>
        </select>
    </div>

    <form method="POST" action="reports/do_report" class="form"
id="reports-form">
        {!! csrf_field() !!}

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    Start Date
                    <input type="date" name="startdate" class="form-control">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    End Date
                    <input type="date" name="enddate" class="form-control">
                </div>
            </div>
        </div>

        <div class="row" id="payers">
            <div class="col-md-6">
                <div class="form-group">
                    Payer
                    <select name="payer_select[]" v-model="payer"
class="form-control" multiple>
                        <option v-repeat="option: payer" value="@{{
option.payer_name }}">
                            @{{option.payer_name}}
                        </option>
                    </select>
                </div>
            </div>
            <div class="col-md-6">
                <div id="patient_div" class="form-group hide">
                    Patient
                    <select name="patient_select[]" v-model="patient"
class="form-control" multiple>
                        <option v-repeat="option: patient" value="@{{
option.patient_full_name }}">
                            @{{option.patient_full_name}}
                        </option>
                    </select>
                </div>
            </div>
        </div>


Gary Wolff
985-778-9474
Skype:  freedomfflow

**Comment by freedomfflow** [comment]
Ok,
I addressed all but 1 issue.  I modified my ajax requests to use the
'request' plugin that is in place with Spark, so that is a little cleaner.
I got rid of the v-on event and instead of manipulating the class
indirectly that way, I'm using a 'v-if' statement to set the class right on
the div I want to show or hide.  Much easier and it works.

So my only issue now is why when I click to select data form my select
boxes that the data gets erased... all the data... as opposed to selecting
it

Thanks

Gary Wolff
985-778-9474
Skype:  freedomfflow

**Comment by freedomfflow** [comment]
And sorry for all this communication as I blindly forge ahead.

I figured out my data disappearing rpoblem... Had my model name the same as
my collection...

Thanks for you initial response... It did send me int he right direction!!

Gary Wolff
985-778-9474
Skype:  freedomfflow
